stages:
  - build
  - test
  - deploy
  - staging
  - production

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OP_APP_DIR: '/prod/softprod/apps/openpype'
  OP_STAGING_PATH: "$OP_APP_DIR/STAGING"
  OP_PROD_PATH: '$OP_APP_DIR/LATEST'
  OP_VERSION_PATH: '$OP_APP_DIR/VERSION_NOT_SET'

workflow:
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG != ""
      variables:
        OP_VERSION_PATH: "$OP_APP_DIR/$CI_COMMIT_TAG"
    - if: $CI_COMMIT_TAG == null || $CI_COMMIT_TAG ==""
      variables:
        OP_VERSION_PATH: "$OP_APP_DIR/$CI_COMMIT_BRANCH/$CI_COMMIT_SHORT_SHA"
    - when: always

.build-centos:
  stage: build
  tags:
    - shell
    - centos
  script:
    # Add python from soft prod
    - echo "Buil then copy to $OP_VERSION_PATH"
    - export PYTHEMP=$(mktemp -d -t ci-XXXXXXXXXX -p ./)
    - rsync -rtl --chmod a+w /prod/softprod/apps/python/3.7.9/linux $PYTHEMP/
    - export PATH="$PYTHEMP/linux/bin:$PATH"
    # Create virtual environment in ./venv
    - ./tools/create_env.sh
    # Get PySide2, ffmpeg, oiio and other tools needed
    - ./tools/fetch_thirdparty_libs.sh
    # Build pype executables in ./build
    - ./tools/build.sh
    # Copy build in softprod
    - mkdir -p $OP_VERSION_PATH/linux
    - rsync -rptl ./build/exe.linux-x86_64-3.7/ $OP_VERSION_PATH/linux/

.build-windows:
  stage: build
  tags:
    - shell
    - windows
  script:
    - echo "Build then copy to $env:OP_VERSION_PATH"
    # - Get-ChildItem -Path Env:\
    - git --version
    - git --exec-path
    - ls C:\Program` Files\Git\mingw64\ssl\certs
    # - git config --global http.sslCAInfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"
    - git config --global http.sslVerify false
    # setup python 3.7.9
    - $env:PATH="c:\prod\softprod\apps\python\3.7.9\windows\;C:\prod\softprod\apps\git-bash\latest\windows\cmd\;"+$env:PATH
    # - [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    # - Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe" -OutFile "c:/temp/python-3.7.9.exe"
    # - c:/temp/python-3.7.9.exe /quiet InstallAllUsers=0 PrependPath=1 Include_test=0

    # - $env:POETRY_HOME="$pwd\.poetry"
    # - $env:POETRY_VERSION="1.1.15"
    # - (Invoke-WebRequest -Uri https://install.python-poetry.org/ -UseBasicParsing).Content | python -
    # - .poetry/bin/poetry update -vvv
    - C:\prod\softprod\apps\git-bash\latest\windows\cmd\git.exe clone --recurse-submodules -- https://github.com/ActiveState/appdirs.git  C:\Gitlab-Runner\builds\zfeUa-YX\0\quad\openpype\OpenPype\.venv\src\appdirs
    - .\tools\create_env.ps1 --verbose
    # - poetry env use
    - .\tools\fetch_thirdparty_libs.ps1
    # - gcm *host*
    - .\tools\build.ps1
    - Copy-Item -Force -Recurse .\build\exe.win-amd64-3.7 $env:OP_VERSION_PATH/windows

build-centos-on-tags:
  extends: .build-centos
  variables:
    VERSION: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: always

build-centos-manual:
  extends: .build-centos
  variables:
    VERSION: $CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "cicd"
      when: manual

build-windows-on-tags:
  extends: .build-windows
  rules:
    - if: $CI_COMMIT_TAG
      when: always

build-windows-manual:
  extends: .build-windows
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "cicd"
      when: manual

.deploy-staged:
  stage: staging
  needs: [build-windows-on-tags, build-centos-on-tags]
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  tags:
    - shell
    - centos
  script:
    - ln -sf $OP_VERSION_PATH $OP_STAGING_PATH

deploy-staged-on-tags:
  extends: .deploy-staged
  needs: [ {job: build-centos-on-tags, optional: false }, {job: build-windows-on-tags, optional: false } ]
  rules:
    - if: $CI_COMMIT_TAG

deploy-staged-manual:
  extends: .deploy-staged
  needs: [ {job: build-centos-manual, optional: true }, {job: build-windows-manual, optional: true } ]
  rules:
    - if: $CI_COMMIT_BRANCH == "cicd"

deploy-prod:
  when: manual
  stage: production
  needs: [{job: deploy-staged-on-tags, optional: true }, {job: deploy-staged-manual, optional: true }]
  tags:
    - shell
    - centos
  script:
    - ln -sf $OP_VERSION_PATH $OP_PROD_PATH
