
stages:
  - build
  - test
  - deploy
  - prod

.cache: &cache_configuration
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build

.build-centos:
  <<: *cache_configuration
  stage: build
  tags: 
    - shell
    - centos
  script:
    # Add python from soft prod 
    - export PYTHEMP=$(mktemp -d -t ci-XXXXXXXXXX -p ./)
    - rsync -rtl --chmod a+w /prod/softprod/apps/python/3.7.9/linux $PYTHEMP/
    - export
    - export PATH="$PYTHEMP/linux/bin:$PATH"
    # Create virtual environment in ./venv
    - ./tools/create_env.sh
    # Get PySide2, ffmpeg, oiio and other tools needed
    - ./tools/fetch_thirdparty_libs.sh
    # build pype executables in .\build\
    - ./tools/build.sh
    # - tar cvzfp ./build.tar.gz ./build

.build-windows:
  <<: *cache_configuration
  stage: build
  only:
    - tags
  tags: 
    - shell
    - windows
  script:
    - $env:PATH="c:\prod\softprod\apps\python\3.7.9\windows;%PATH%"
    - python -v
    - .\tools\create_env.ps1
    - .\tools\fetch_thirdparty_libs.ps1
    - .\tools\build.ps1

build-centos-on-tags:
  extends: .build-centos
  only: [tags]

build-centos-manual:
  extends: .build-centos
  when: manual

build-windows-on-tags:
  extends: .build-windows
  only: [tags]

build-windows-manual:
  extends: .build-windows
  when: manual


.deploy-staged:
  <<: *cache_configuration
  stage: deploy
  environment:
    name: staging
  tags: 
    - shell
    - centos
  script:
    - ls ./build/
    - version=$(git describe --match v?.* --all --always | sed -e 's/tags\///g')
    - mkdir -p /prod/softprod/apps/openpype/$version/linux/
    - rsync -rptl ./build/exe.linux-x86_64-3.7/ /prod/softprod/apps/openpype/$version/linux/

deploy-staged-on-tags:
  extends: .deploy-staged
  needs: [ {job: build-centos-on-tags, optional: false }, {job: build-windows-on-tags, optional: false } ]
  rules:
    - if: $CI_COMMIT_TAG

deploy-staged-manual:
  extends: .deploy-staged
  needs: [ {job: build-centos-manual, optional: true }, {job: build-windows-manual, optional: true } ]
  rules:
    - if: $CI_COMMIT_BRANCH
  

deploy-prod:
  when: manual
  stage: prod
  environment:
    name: production
  needs: [deploy-staged-on-tags, {job: deploy-staged-manual, optional: true }]
  tags: 
    - shell
    - centos
  script:
    - pwd
