# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
image: centos7:latest

stages:
  - build
  - test
  - deploy

build-centos:
  stage: build
  tags: docker
  image: centos7:latest
  before_script:
    - sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - sudo yum install centos-release-scl
    - sudo yum install bash which git devtoolset-7-gcc* \
        make cmake curl wget gcc zlib-devel bzip2 \
        bzip2-devel readline-devel sqlite sqlite-devel \
        openssl-devel tk-devel libffi-devel qt5-qtbase-devel \
        patchelf  
  script:
    - curl https://pyenv.run | bash
    # you can add those to ~/.bashrc
    - export PATH="$HOME/.pyenv/bin:$PATH"
    - eval "$(pyenv init -)"
    - eval "$(pyenv virtualenv-init -)"
    # reload shell
    - exec $SHELL
    # install Python 3.7.10
    # python will be downloaded and build so please make sure
    # you have all necessary requirements installed (see below).
    - pyenv install -v 3.7.10
    # change path to pype 3
    - cd /path/to/pype-3
    # set local python version
    - pyenv local 3.7.10
