name: Bug Report
description: File a bug report
title: 'Bug: '
labels:
  - 'type: bug'
body:
  - type: markdown
    attributes:
      value: "Vous n'êtes plus au bon endroit pour créer un ticket. RDV dans le repo issue tracker"
  - type: dropdown
    attributes:
      label: Si jamais vous avez un doute, demandez à...
      options:
        - Louise
        - Louise
    
