name: Bug Report
description: File a bug report
title: 'Bug: '
labels:
  - 'type: bug'
body:
  - type: markdown
    attributes:
      value: "*Thanks for taking the time to fill out this bug report! Please fill this form carefully in order to help us work more efficiently.*"
  - type: markdown
    attributes:
      value: "## 1. Informations"
  - type: dropdown
    attributes:
      label: Before posting a new ticket, have you looked through the documentation to find an answer?
      description: You can fin the documentation in the fix wiki > fixwiki/drive/tools/openpype/decouverte_openpype/
      options:
        - Not yet
        - Yes I have
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Have you looked through the existing tickets to find any related issues ?
      options:
        - Not yet
        - Yes I have
    validations:
      required: true
  - type: input
    attributes:
      label: 'Author of the bug'
      description: This person may be contacted for additionnal informations
  - type: dropdown
    id: _version
    attributes:
      label: Version
      description: What version are you running? Look to OpenPype Tray
      options:
        - 3.15.12-quad.4.1
        - 3.15.12-quad.4.0
        - 3.15.12-quad.3.0
        - 3.15.12-quad.2.0
        - 3.15.12-quad.0.2
        - 3.15.12-quad.0.1
        - 3.15.12
        - 3.15.12-nightly.4
        - 3.15.12-nightly.3
        - 3.15.12-nightly.2
        - 3.15.12-nightly.1
        - 3.15.11
        - 3.15.11-nightly.5
        - 3.15.11-nightly.4
        - 3.15.11-nightly.3
        - 3.15.11-nightly.2
        - 3.15.11-nightly.1
        - 3.15.10
        - 3.15.10-nightly.2
        - 3.15.10-nightly.1
        - 3.15.9
        - 3.15.9-nightly.2
        - 3.15.9-nightly.1
        - 3.15.8
        - 3.15.8-nightly.3
        - 3.15.8-nightly.2
        - 3.15.8-nightly.1
        - 3.15.7
        - 3.15.7-nightly.3
        - 3.15.7-nightly.2
        - 3.15.7-nightly.1
        - 3.15.6
        - 3.15.6-nightly.3
        - 3.15.6-nightly.2
        - 3.15.6-nightly.1
        - 3.15.5
        - 3.15.5-nightly.2
        - 3.15.5-nightly.1
        - 3.15.4
        - 3.15.4-nightly.3
        - 3.15.4-nightly.2
        - 3.15.4-nightly.1
        - 3.15.3
        - 3.15.3-nightly.4
        - 3.15.3-nightly.3
        - 3.15.3-nightly.2
        - 3.15.3-nightly.1
        - 3.15.2
        - 3.15.2-nightly.6
        - 3.15.2-nightly.5
        - 3.15.2-nightly.4
        - 3.15.2-nightly.3
        - 3.15.2-nightly.2
        - 3.15.2-nightly.1
        - 3.15.1
        - 3.15.1-nightly.6
        - 3.15.1-nightly.5
        - 3.15.1-nightly.4
        - 3.15.1-nightly.3
        - 3.15.1-nightly.2
        - 3.15.1-nightly.1
        - 3.15.0
        - 3.15.0-nightly.1
        - 3.14.11-nightly.4
        - 3.14.11-nightly.3
        - 3.14.11-nightly.2
        - 3.14.11-nightly.1
        - 3.14.10
        - 3.14.10-nightly.9
        - 3.14.10-nightly.8
        - 3.14.10-nightly.7
        - 3.14.10-nightly.6
        - 3.14.10-nightly.5
        - 3.14.10-nightly.4
        - 3.14.10-nightly.3
        - 3.14.10-nightly.2
        - 3.14.10-nightly.1
        - 3.14.9
        - 3.14.9-nightly.5
        - 3.14.9-nightly.4
        - 3.14.9-nightly.3
        - 3.14.9-nightly.2
        - 3.14.9-nightly.1
        - 3.14.8
        - 3.14.8-nightly.4
        - 3.14.8-nightly.3
        - 3.14.8-nightly.2
        - 3.14.8-nightly.1
        - 3.14.7
        - 3.14.7-nightly.8
        - 3.14.7-nightly.7
        - 3.14.7-nightly.6
        - 3.14.7-nightly.5
        - 3.14.7-nightly.4
        - 3.14.7-nightly.3
        - 3.14.7-nightly.2
        - 3.14.7-nightly.1
        - 3.14.6
        - 3.14.6-nightly.3
        - 3.14.6-nightly.2
        - 3.14.6-nightly.1
        - 3.14.5
        - 3.14.5-nightly.3
        - 3.14.5-nightly.2
        - 3.14.5-nightly.1
        - 3.14.4
    validations:
      required: true
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What platform you are running OpenPype on?
      description: |
        Please specify the operating systems you are running OpenPype with.
      multiple: true
      options:
        - Windows
        - Linux / Centos
        - Linux / Ubuntu
        - Linux / RedHat
        - MacOS
  - type: markdown
    attributes:
      value: "## 2. Bug behavior"
  - type: textarea
    attributes:
      label: 'Current Behavior:'
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected Behavior:'
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What type of bug is it ?
      options:
        - Happened only once in a particular configuration
        - Happens everytime with different configurations
  - type: input
    attributes:
      label: 'Which project / workfile / asset / ...'
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 'Steps To Reproduce:'
      description: Steps to reproduce the behavior.
      placeholder: |
        1. How did the configuration look like
        2. What type of action was made
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## 3. Other informations"
  - type: textarea
    id: logs
    attributes:
      label: 'Relevant log output:'
      description: >-
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context:'
      description: Add any other context about the problem here.
