name: Enhancement
description: form
title: 'Enhancement: '
labels:
  - 'type: enhancement'
body:
  - type: markdown
    attributes:
      value: "Merci de remplir le formulaire dans le repo issue tracker"
